import './globals.css'
import SiteMenu from '@/components/SiteMenu'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <SiteMenu />
      </body>
    </html>
  )
}
